/**
 * Uploads a file directly to a Supabase signed URL via HTTP PUT.
 * This bypasses our standard `api` axios instance because we don't
 * want to send our JWT Bearer token to AWS/Supabase S3 endpoints.
 * 
 * @param {string} signedUrl The secure upload URL generated by the backend
 * @param {File} file The native browser File object to upload
 */
export const uploadFileToSupabase = async (signedUrl, file) => {
  const response = await fetch(signedUrl, {
    method: 'PUT',
    headers: {
      'Content-Type': file.type || 'application/octet-stream',
    },
    body: file,
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Upload failed: ${response.status} ${errorText}`);
  }

  return response;
};
